{"errorMessage": "'dict' object has no attribute 'startswith'", "errorType": "AttributeError", "requestId": "9e6cf767-ec66-4e7a-af01-45010bb86718", "stackTrace": ["  File \"/var/task/chalice/app.py\", line 1753, in __call__\n    return self.handler(event_obj)\n", "  File \"/var/task/chalice/app.py\", line 1699, in __call__\n    return self._original_func(event.to_dict(), event.context)\n", "  File \"/var/task/app.py\", line 42, in main\n    deploy_reports(splunkConfig)\n", "  File \"/var/task/chalicelib/deploy_reports.py\", line 54, in deploy_reports\n    service.saved_searches.create(report_name, report_content)\n", "  File \"/var/task/splunklib/client.py\", line 3459, in create\n    return Collection.create(self, name, search=search, **kwargs)\n", "  File \"/var/task/splunklib/client.py\", line 1700, in create\n    response = self.post(name=name, **params)\n", "  File \"/var/task/splunklib/client.py\", line 937, in post\n    return self.service.post(path, owner=owner, app=app, sharing=sharing, **query)\n", "  File \"/var/task/splunklib/binding.py\", line 292, in wrapper\n    return request_fun(self, *args, **kwargs)\n", "  File \"/var/task/splunklib/binding.py\", line 73, in new_f\n    val = f(*args, **kwargs)\n", "  File \"/var/task/splunklib/binding.py\", line 782, in post\n    all_headers = headers + self.additional_headers + self._auth_headers\n", "  File \"/var/task/splunklib/binding.py\", line 542, in _auth_headers\n    if self.token.startswith('Splunk '):\n"]}